### PR TITLE
Rework vesting origin & audit fixes

### LINKED ISSUE #773: bonded-finance: Comment (assumption) does not match reality
**Rating: None**

# Description
A comment inside the `do_bond` function in `frame/bonded-finance/src/lib.rs` contains an incorrect description of a previously applied constraint.

The comment indicates that `nb_of_bonds < offer.nb_of_bonds` holds, while in fact, `nb_of_bonds <= offer.nb_of_bonds` holds.

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/bonded-finance/src/lib.rs#L369-L370

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/bonded-finance/src/lib.rs#L322-L322

# Impact
This does not have a security impact, as the error is in a comment.

Nevertheless, the comment could mislead a future developer about the applied constraint.

# Recommendation
We recommend changing the comment to match the previously applied constraint, in order to prevent future confusion.

---

**Disclaimer:**
This vulnerability was found using a combination of code-review and limited penetration testing. The final impact may depend on the larger (production) environment. The above recommendation is included to help mitigate or resolve this issue, but may not necessarily be a complete or final solution.

### PR DESCRIPTION
**Pull request by hussein-aitlahcen**
This PR must fix #773 #772 #771 

I also modified the Vesting pallet not to use the `origin` account as source account for the transfer.
This allow us to define the `RootOrHalfCouncil` as `VesterTransferOrigin` in the runtimes.
Cross-pallet call is still permisionless.

This PR also remove the usage of `self` in `CurrencyId` to allow us to represent amounts without confusion (A unit of any currency was previously defined as `CurrencyId.PICA.unit()` while it is now represented as `CurrencyId::unit()` as all currencies are normalized to the same number of decimals within our system.

### CODE REVIEW

File: frame/crowdloan-rewards/src/lib.rs [hunk 1]
```diff
@@ -114,7 +114,7 @@ pub mod pallet {
 	pub enum Error<T> {
 		NotInitialized,
 		AlreadyInitialized,
-		InvalidInitializationBlock,
+		BackToTheFuture,
```
Comment (benluelo) [inline frame/crowdloan-rewards/src/lib.rs:117]: nice

**Review by benluelo — APPROVED** [review]

File: frame/bonded-finance/src/lib.rs [hunk 2]
```diff
@@ -312,10 +312,12 @@ pub mod pallet {
...
 		) -> Result<T::BondOfferId, DispatchError> {
-			let offer_id = BondOfferCount::<T>::try_mutate(|offer_id| -> Result<T::BondOfferId, DispatchError> {
-				*offer_id = offer_id.safe_add(&T::BondOfferId::one())?;
-				Ok(*offer_id)
-			})?;
+			let offer_id = BondOfferCount::<T>::try_mutate(
+				|offer_id| -> Result<T::BondOfferId, DispatchError> {
+					*offer_id = offer_id.safe_add(&T::BondOfferId::one())?;
+					Ok(*offer_id)
+				},
```
Comment (benluelo) [inline frame/bonded-finance/src/lib.rs:319]: Perhaps somewhat unrelated to this PR, but we use this "try increment storage" pattern a lot, maybe we could extract it to a helper function in `composable-helpers`?

Comment (hussein-aitlahcen) [reply frame/bonded-finance/src/lib.rs:319]: I think it's pretty fair to extract that, yes

**Review by vimukthi-git — APPROVED** [review]
LGTM
